### ISSUE TITLE
Header

### ISSUE THREAD

**Issue by mmalaquiasdev** [mmalaquiasdev/rock-paper-scissors-game#1]
# Feature request

## Is your feature request related to a problem? Please describe.

We need a central title on the game page, following the image template used in that issue

## Describe the solution you'd like

```html
    <header><h1>Rock Paper Scissors</h1></header>
```

```css
code {
	font-family: 'Source Code Pro', monospace;
	font-size: 12px;
}

a {
	font-family: 'Source Code Pro', monospace;
	color: #ffcc99;
}

a:hover {
	color: #ffba76;

header {
	background: #fff;
	padding: 20px;
}

header h1 {
	color: #444;
	text-align: center;
	font-weight: 100;
}
```
## Additional context

![](https://i.ibb.co/fGg1DVZ/Screen-Shot-2019-02-16-at-19-26-48.png)
