### ISSUE TITLE
Body

### ISSUE THREAD

**Issue by mmalaquiasdev** [mmalaquiasdev/rock-paper-scissors-game#2]
# Feature request

## Describe.

We need an area in the html body to insert the game components

## Describe the solution you'd like

```css
html {
	box-sizing: border-box;
}

*,
*:before,
*:after {
	box-sizing: inherit;
}

* {
	margin: 0;
	padding: 0;
}

body {
	background: #24272e;
	color: #fff;
	font-family: "Roboto", sans-serif;
}
```
## Additional context

![](https://i.ibb.co/1vC2106/Screen-Shot-2019-02-16-at-19-33-58.png)
