### ISSUE TITLE
Score Board

### ISSUE THREAD

**Issue by mmalaquiasdev** [mmalaquiasdev/rock-paper-scissors-game#3]
# Feature request

## Is your feature request related to a problem? Please describe.

Develop a component that shows the user and machine points.

## Describe the solution you'd like

```html
<div class="score-board">
      <div id="user-label" class="badge">user</div>
      <div id="computer-label" class="badge">comp</div>
      <span id="user-score">0</span> : <span id="computer-score">0</span>
    </div>
```

```css
.score-board {
	border: 3px solid #fff;
	width: 300px;
	margin: 40px auto;
	font-size: 40px;
	border-radius: 4px;
	text-align: center;
	padding: 15px 20px;
	position: relative;
}

.badge {
	background: #e2584d;
	text-transform: uppercase;
	font-size: 14px;
	padding: 10px 6px;
}
```

## Additional context

![](https://i.ibb.co/gv50fHH/Screen-Shot-2019-02-16-at-19-47-23.png)

![](https://i.ibb.co/LYsyHRr/Screen-Shot-2019-02-16-at-20-03-58.png)
