### ISSUE TITLE
Result

### ISSUE THREAD

**Issue by mmalaquiasdev** [mmalaquiasdev/rock-paper-scissors-game#4]
# Feature request

## Is your feature request related to a problem? Please describe.

Below the points table I want to display personalized messages of: victory, defeat and tie

## Describe the solution you'd like

```html
<div class="result"><p>Paper covers rock. You win!</p></div>
```

```css
.result {
	font-weight: 300;
	text-align: center;
	font-size: 32px;
	line-height: 40px;
}

.result {
	line-height: 50px;
}
```

## Additional context

![](https://i.ibb.co/2spQsSH/Screen-Shot-2019-02-16-at-19-57-50.png)

![](https://i.ibb.co/HGJkrb5/Screen-Shot-2019-02-16-at-20-02-46.png)
