### ISSUE TITLE
Choices

### ISSUE THREAD

**Issue by mmalaquiasdev** [mmalaquiasdev/rock-paper-scissors-game#5]
# Feature request

## Is your feature request related to a problem? Please describe.

Create an area in the layout where we'll add game action options

## Describe the solution you'd like

```html
<div class="choices"></div>
```

```css
.choices {
	margin: 0 auto;
	text-align: center;
	padding: 40px 0;
}

.choice {
	display: inline-block;
	border: 3px solid #fff;
	border-radius: 50%;
	padding: 10px;
	margin: auto 10px;
	transition: all 0.3s ease;
}

.choice img {
	filter: invert(100%);
}
```
